# Generated by Django 3.0.3 on 2020-03-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userupimage',
            table='Userupimage',
        ),
    ]
