# Generated by Django 3.0.3 on 2020-03-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200316_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='f_area',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='flower',
            name='f_branch',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='flower',
            name='f_description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='flower',
            name='f_feature',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='flower',
            name='f_latin_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='flower',
            name='f_nickname',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='flower',
            name='f_sire',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
