# Generated by Django 3.0.3 on 2020-03-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200317_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='f_latin_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='flower',
            name='f_nickname',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
