# Generated by Django 3.0.3 on 2020-03-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200317_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='f_latin_name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
